vm: "fvm"
device:
  android:
    flavor: "automateGoogle"
    device_id: "emulator-5554"
    device_name: "emulator-5554"
  ios:
    flavor: "automate"
    device_name: "iPhone 14 Pro Max"
report:
  name: "report/ui-test-{}.html"
tests:
  - "authentication/test.dart"